### ISSUE TITLE
Load balancing message delay

### ISSUE THREAD

**Issue by lirong-Lee** [apache/rocketmq-client-cpp#340]
Two clients A and B subscribe to a topic, and a Producer continuously pushes it. 
    When A receives a message, kill A and observe whether the message is pushed to B. If it is pushed to B, pull up A, and kill when A receives the message Drop A and repeat this operation. 
    The first few messages will be pushed to B. When A does not start, some messages will accumulate. Will be pushed to B in half an hour.

**Comment by ifplusor** [comment]
@lirong-Lee I did not understand what you mean, you can say it more clearly?

**Comment by lirong-Lee** [comment]
The problem is: if a CPushConsumer is permanently closed, it may cause some messages to be delayed for half an hour.
The specific operation is：
1、Two clients A and B CLUSTERING subscribe to a topic, and a Producer continuously pushes it. 
2、When A receives a message, kill A
3、observe whether the message is pushed to B. If it is pushed to B, pull up A
4、Repeat 2 and 3 operations
5、After repeating operations 2 and 3 several times, turn off A, B will not receive a lot of messages
6、The news is piled up on the broker, and then pushed to B after half an hour

My broker uses rocketmq-4.7.1, this operation is complete.

**Comment by ifplusor** [comment]
Can you try this with new version in re_dev branch?

**Comment by lirong-Lee** [comment]
Hi Ifplusor

I use re_dev branch to test it is normal and will not be delayed. Is there any design difference between this branch and master?

**Comment by ifplusor** [comment]
@lirong-Lee The branch of re_dev is a refactored version, it has many improvements, and the dependence of boost was removed. It will be master in the future.

**Comment by lirong-Lee** [comment]
@Ifplusor PushConsumer in the example of rd_dev uses BROADCASTING subscription, it will report an error and cannot receive the message,Use CLUSTERING to receive messages normally.

The error message is：
[MQClientException] msg: create offset store dir failed: /home/lirongLee/.rocketmq_offsets/::1@DEFAULT/myGroup, error: -1, in </home/lirongLee/MySoft/rocketmq/tls/rocketmq-client-cpp-re_dev/src/consumer/LocalFileOffsetStore.cpp:44>

**Comment by ifplusor** [comment]
@lirong-Lee Please check which dir create failed in path of "/home/lirongLee/.rocketmq_offsets/::1@DEFAULT/myGroup"

**Comment by lirong-Lee** [comment]
@ifplusor I used mkdir -p /home/lirongLee/.rocketmq_offsets/::1@DEFAULT/myGroup in advance.
This will not report the error log, but will not receive the message.
I think it will not be caused by the failure of the directory creation.

**Comment by ifplusor** [comment]
@lirong-Lee I have fixed this issue, you can update the source code.

**Comment by lirong-Lee** [comment]
@ifplusor 
No error will be reported when running now, but the message cannot be received using BROADCASTING, and the message can be received using CLUSTER.
BROADCASTING should still have problems.

**Comment by ifplusor** [comment]
@lirong-Lee I have fixed it, again.

**Comment by lirong-Lee** [comment]
@ifplusor The problem has been solved
